    <div class="span2">
    </div>
    <div class="span10">
        <div id="content">
			<div class="page-header">
                <h4>关于 VAuditDemo</h4>
                <hr>
				<p>
                    <b>[测试环境]</b>
                    <br />
					<ul>
                        <li>Apache 3.2.5 beta</li>
						<li>PHP 6.6.30</li>
					</ul>
                    <b>[php配置文件中]</b>
                    <br />
					<ul>
                        <li>allow_url_include = Off</li>
                        <li>allow_url_fopen = Off</li>
                        <li>magic_quotes_gpc = Off</li>
					</ul>
                </p>
                <hr>
                <p>
                    <b>[联系]</b>
                    <br />
                    Telegram: <a href="https://telegram.me/virink">@virink</a>
                    <br />
                    Email: virink@outlook.com
                    <br />
					欢迎一起交流学习
                </p>    
            </div>
        </div>
    </div>
<!--
<?php
show_source(__FILE__);
?>
-->